# Describes the format for available webostv services

get_command:
  description: "Send a generic http get command."
  fields:
    entity_id:
      description: Name(s) of the denonavr entities where to run the API method.
      example: "media_player.living_room_receiver"
    command:
      description: Endpoint of the command, including associated parameters.
      example: "/goform/formiPhoneAppDirect.xml?RCKSK0410370"

tone_control_enable:
  description: "Enable Tone control to be able to change Bass and/or Treble levels."
  fields:
    entity_id:
      description: "Name(s) of the denonavr entities where to run the API method."
      example: "media_player.living_room_receiver"
    is_tone_control_enabled:
      description: "True/false for enable/disable."
      example: "true"

bass_up:
  description: "Turn a media player bass level up."
  fields:
    entity_id:
      description: "Name(s) of entities to turn the level of bass up."
      example: "media_player.living_room_receiver"

bass_down:
  description: "Turn a media player bass level down."
  fields:
    entity_id:
      description: "Name(s) of entities to turn the level of bass down."
      example: "media_player.living_room_receiver"

treble_up:
  description: "Turn a media player treble level up."
  fields:
    entity_id:
      description: "Name(s) of entities to turn the level of treble up."
      example: "media_player.living_room_receiver"

treble_down:
  description: "Turn a media player treble level down."
  fields:
    entity_id:
      description: "Name(s) of entities to turn the level of treble down."
      example: "media_player.living_room_receiver"
